#ifndef __ACTION_LIST_H__
#define __ACTION_LIST_H__

#define ACTION_BASIC_COME 0
#define ACTION_BASIC_CURE 1
#define ACTION_BASIC_EAT 2
#define ACTION_BASIC_REST 3
#define ACTION_BASIC_RUN 4
#define ACTION_BASIC_SLEEP 5
#define ACTION_BASIC_STOP 6
#define ACTION_BASIC_WAKE 7
#define ACTION_BASIC_POOP 8
#define ACTION_TRAINING_CLEANPOOP 100
#define ACTION_TRAINING_ROPE 101
#define ACTION_TRAINING_RUNNING 102
#define ACTION_PLAYING_PLAY 200
#define ACTION_PLAYING_SWING 201
#define ACTION_EXTRA_DIE 900
#define ACTION_EXTRA_UNKNOWN 901

#endif