#pragma once

#ifndef WINSIZE_X
#define WINSIZE_X 1280
#endif

#ifndef WINSIZE_Y
#define WINSIZE_Y 720
#endif

#define TILE_X 20
#define TILE_Y 20
#define TILESIZE_X WINSIZE_X/TILE_X
#define TILESIZE_Y TILESIZE_X/2
#define GAME_SCALE 2.f

#define BUTTON_OPTION_X (WINSIZE_X-80)
#define BUTTON_OPTION_Y (WINSIZE_Y-80)
#define BUTTON_FRIEND_X (WINSIZE_X-80)
#define BUTTON_FRIEND_Y (WINSIZE_Y-240)
#define BUTTON_MULTI_PRACTICE_X (WINSIZE_X-80)
#define BUTTON_MULTI_PRACTICE_Y (WINSIZE_Y-400)
#define SPEAKER_X (WINSIZE_X/2)
#define SPEAKER_Y (WINSIZE_Y/10)
enum LAYERS { INGAME=1000, LOADING, LOGIN, PREPARING, LAYER_END };